PACKAGE=runtime
PROG=	reboot

LINKS=	${BINDIR}/reboot ${BINDIR}/halt \
	${BINDIR}/reboot ${BINDIR}/fastboot \
	${BINDIR}/reboot ${BINDIR}/fasthalt \
	${BINDIR}/reboot ${BINDIR}/nextboot

.include <bsd.prog.mk>
