PROG_CXX=	lldb-tblgen

SRCDIR=		lldb/utils/TableGen
SRCS+=		LLDBOptionDefEmitter.cpp
SRCS+=		LLDBPropertyDefEmitter.cpp
SRCS+=		LLDBTableGen.cpp
SRCS+=		LLDBTableGenUtils.cpp

.include "../llvm.prog.mk"
