SRCS+=	i386_get_fsbase.c i386_get_gsbase.c i386_get_ioperm.c i386_get_ldt.c \
	i386_set_fsbase.c i386_set_gsbase.c i386_set_ioperm.c i386_set_ldt.c \
	i386_clr_watch.c i386_set_watch.c i386_vm86.c \
	rfork_thread.S pdrfork_thread.S

MDASM=	vfork.S cerror.S getcontext.S syscall.S
