.\"-
.\" SPDX-License-Identifier: BSD-2-Clause
.\"
.\" vidcontrol - a utility for manipulating the vt video driver
.\"
.\" Redistribution and use in source and binary forms, with or without
.\" modification, are permitted provided that the following conditions
.\" are met:
.\" 1. Redistributions of source code must retain the above copyright
.\"    notice, this list of conditions and the following disclaimer.
.\" 2. Redistributions in binary form must reproduce the above copyright
.\"    notice, this list of conditions and the following disclaimer in the
.\"    documentation and/or other materials provided with the distribution.
.\"
.Dd November 22, 2025
.Dt VIDCONTROL 1
.Os
.Sh NAME
.Nm vidcontrol
.Nd system video console control and configuration utility
.Sh SYNOPSIS
.Nm
.Op Fl Cx
.Op Fl b Ar color
.Op Fl c Ar appearance
.Oo
.Fl f
.Oo
.Op Ar size
.Ar file
.Oc
.Oc
.Op Fl g Ar geometry
.Op Fl h Ar size
.Op Fl i Cm active | adapter | mode
.Op Fl M Ar char
.Op Fl m Cm on | off
.Op Fl r Ar foreground Ar background
.Op Fl S Cm on | off
.Op Fl s Ar number
.Op Fl T Cm xterm | cons25
.Op Fl t Ar N | Cm off
.Op Ar mode
.Op Ar foreground Op Ar background
.Op Cm show
.Sh DESCRIPTION
The
.Nm
utility is used to set various options for the
.Xr vt 4
console driver,
such as video mode, colors, cursor shape, font, and screen blanking timeout.
Only a small subset of options is supported by
.Xr vt 4 .
Unsupported options lead to error messages, typically including
the text "Inappropriate ioctl for device".
.Pp
The following command line options are supported:
.Bl -tag -width indent
.It Ar mode
Select a new video mode.
The modes currently recognized are:
.Ar 80x25 ,
.Ar 80x30 ,
.Ar 80x43 ,
.Ar 80x50 ,
.Ar 80x60 ,
.Ar 132x25 ,
.Ar 132x30 ,
.Ar 132x43 ,
.Ar 132x50 ,
.Ar 132x60 ,
.Ar VGA_40x25 ,
.Ar VGA_80x25 ,
.Ar VGA_80x30 ,
.Ar VGA_80x50 ,
.Ar VGA_80x60 ,
.Ar VGA_90x25 ,
.Ar VGA_90x30 ,
.Ar VGA_90x43 ,
.Ar VGA_90x50 ,
.Ar VGA_90x60 ,
.Ar EGA_80x25 ,
.Ar EGA_80x43 ,
.Ar VESA_132x25 ,
.Ar VESA_132x43 ,
.Ar VESA_132x50 ,
.Ar VESA_132x60 .
.\"The graphic mode
.\".Ar VGA_320x200
.\"and
The raster text mode
.Ar VESA_800x600
can also be chosen.
Alternatively, a mode can be specified with its number by using a mode name of
the form
.Li MODE_ Ns Aq Ar NUMBER .
A list of valid mode numbers can be obtained with the
.Fl i Cm mode
option.
See
.Sx Video Mode Support
below.
.It Ar foreground Op Ar background
Change colors when displaying text.
Specify the foreground color
(e.g.,
.Dq vidcontrol white ) ,
or both a foreground and background colors
(e.g.,
.Dq vidcontrol yellow blue ) .
Use the
.Cm show
command below to see available colors.
.It Cm show
See the supported colors on a given platform.
.It Fl b Ar color
Set border color to
.Ar color .
This option may not be always supported by the video driver.
.It Fl C
Clear the history buffer.
.It Fl c Ar setting Ns Op , Ns Ar setting ...
Change the cursor appearance.
The change is specified by a non-empty comma-separated list of
.Ar setting Ns s .
Each
.Ar setting
overrides or modifies previous ones in left to right order.
.Pp
The following override
.Ar setting Ns s
are available:
.Bl -tag -width indent
.It Cm normal
Set to a block covering 1 character cell,
with a configuration-dependent coloring
that should be at worst inverse video.
.It Cm destructive
Set to a blinking sub-block with
.Cm height
scanlines starting at
.Cm base .
The name
.Dq destructive
is bad for backwards compatibility.
This
.Ar setting
should not force destructiveness,
and it now only gives destructiveness in some
configurations (typically for hardware cursors
in text mode).
Blinking limits destructiveness.
This
.Ar setting
should now be spelled
.Cm normal , Ns Cm blink , Ns Cm noblock .
A non-blinking destructive cursor would be unusable,
so old versions of
.Nm
did not support it,
and this version does not have an override for it.
.It Cm base Ns = Ns Ar value , Cm height Ns = Ns Ar value
Set the specified scanline parameters.
These parameters are only active in
.Cm noblock
mode.
.Cm value
is an integer in any base supported by
.Xr strtol 3 .
Setting
.Cm height
to 0 turns off the cursor in
.Cm noblock
mode.
Negative
.Ar value Ns s
are silently ignored.
Positive
.Ar value Ns s
are clamped to fit in the character cell when the cursor is drawn.
.El
.Pp
The following modifier
.Ar setting Ns s
are available:
.Bl -tag -width indent
.It Cm blink , noblink
Set or clear the blinking attribute.
This is not quite backwards compatible.
In old versions of
.Nm , Cm blink
was an override to a blinking block.
.It Cm block , noblock
Set or clear the
.Cm block
attribute.
This attribute is the inverse of the flag
.Dv CONS_CHAR_CURSOR
in the implementation.
It deactivates the scanline parameters,
and expresses a preference for using a
simpler method of implementation.
Its inverse does the opposite.
When the scanline parameters give a full block,
this attribute reduces to a method selection bit.
The
.Cm block
method tends to give better coloring.
.It Cm hidden , nohidden
Set or clear the hidden attribute.
.El
.Pp
The following (non-sticky) flags control application of the
.Ar setting Ns s :
.Bl -tag -width indent
.It Cm charcolors
Apply
.Cm base
and
.Cm height
to the (character) cursor's list of preferred colors instead of its shape.
Beware that the color numbers are raw VGA palette indexes,
not ANSI color numbers.
The indexes are reduced mod 8, 16 or 256,
or ignored,
depending on the video mode and renderer.
.It Cm mousecolors
Colors for the mouse cursor in graphics mode.
Like
.Cm charcolors ,
except there is no preference or sequence;
.Cm base
gives the mouse border color and
.Cm height
gives the mouse interior color.
Together with
.Cm charcolors ,
this gives 2 selection bits which select between
only 3 of 4 sub-destinations of the 4 destinations selected by
.Cm default
and
.Cm local
(by ignoring
.Cm mousecolors
if
.Cm charcolors
is also set).
.It Cm default
Apply the changes to the default settings and then to the active settings,
instead of only to the active settings.
Together with
.Cm local ,
this gives 2 selection bits which select between 4 destinations.
.It Cm shapeonly
Ignore any changes to the
.Cm block
and
.Cm hidden
attributes.
.It Cm local
Apply the changes to the current vty.
The default is to apply them to a global place
and copy from there to all vtys.
.It Cm reset
Reset everything.
The default is to not reset.
When the
.Cm local
parameter is specified, the current local settings are reset
to default local settings.
Otherwise, the current global settings are reset to default
global settings and then copied to the current and default
settings for all vtys.
.It Cm show
Show the current changes.
.El
.It Fl f Op Ar file
Load a vt font from
.Ar file .
The font file must be in the format described by
.Xr vtfontcvt 8 .
If no file is given, restore the default font.
The optional legacy font-size argument is accepted but ignored.
The menu-driven
.Xr vidfont 1
utility can also select a font.
.It Fl g Ar geometry
Set the
.Ar geometry
of the text mode for the modes with selectable
geometry.
Currently only raster modes, such as
.Ar VESA_800x600 ,
support this option.
See also
.Sx Video Mode Support
and
.Sx EXAMPLES
below.
.It Fl h Ar size
Set the size of the history (scrollback) buffer to
.Ar size
lines.
.It Fl i Cm active
Shows the active vty number.
.It Fl i Cm adapter
Shows info about the current video adapter.
.It Fl i Cm mode
Shows the possible video modes with the current video hardware.
.It Fl M Ar char
Sets the base character used to render the mouse pointer to
.Ar char .
.It Fl m Cm on | off
Switch the mouse pointer
.Cm on
or
.Cm off .
Used together with the
.Xr moused 8
daemon for text mode cut & paste functionality.
.It Fl r Ar foreground background
Change reverse mode colors to
.Ar foreground
and
.Ar background .
.It Fl S Cm on | off
Turn vty switching on or off.
When vty switching is off,
attempts to switch to a different virtual terminal will fail.
(The default is to permit vty switching.)
This protection can be easily bypassed when the kernel is compiled with
the
.Dv DDB
option.
However, you probably should not compile the kernel debugger on a box which
is supposed to be physically secure.
.It Fl s Ar number
Set the active vty to
.Ar number .
.It Fl T Cm xterm | cons25
Switch between xterm and cons25 style terminal emulation.
.It Fl t Ar N | Cm off
Set the screensaver timeout to
.Ar N
seconds, or turns it
.Cm off .
.It Fl x
Use hexadecimal digits for output.
.El
.Sh VIDEO OUTPUT CONFIGURATION
.Ss Boot Time Configuration
You may set the following variables in
.Pa /etc/rc.conf
or
.Pa /etc/rc.conf.local
in order to configure the video output at boot time.
.Pp
.Bl -tag -width foo_bar_var -compact
.It Ar blanktime
Sets the timeout value for the
.Fl t
option.
.It Ar font8x16 , font8x14 , font8x8
Specifies font files for the
.Fl f
option.
.El
.Pp
See
.Xr rc.conf 5
for more details.
.Ss Driver Configuration
The video card driver may let you change default configuration
options, such as the default font, so that you do not need to set up
the options at boot time.
See video card driver manuals, (e.g.,
.Xr vga 4 )
for details.
.Sh FILES
.Bl -tag -width /usr/share/vt/fonts/* -compact
.It Pa /usr/share/vt/fonts/*
Font files.
.El
.Sh EXAMPLES
Load an installed vt font:
.Pp
.Dl vidcontrol -f /usr/share/vt/fonts/vgarom-8x16.fnt
.Pp
The directory and extension may be omitted:
.Pp
.Dl vidcontrol -f vgarom-8x16
.Pp
Restore the default font:
.Pp
.Dl vidcontrol -f
.Sh SEE ALSO
.Xr kbdcontrol 1 ,
.Xr vidfont 1 ,
.Xr keyboard 4 ,
.Xr screen 4 ,
.Xr vga 4 ,
.Xr vt 4 ,
.Xr rc.conf 5 ,
.Xr kldload 8 ,
.Xr moused 8 ,
.Xr watch 8
.Pp
The various
.Pa scr2*
utilities in the
.Pa graphics
and
.Pa textproc
categories of the
.Em "Ports Collection" .
.Sh AUTHORS
.An S\(/oren Schmidt Aq Mt sos@FreeBSD.org
.An Sascha Wildner Aq Mt saw@online.de
.Sh CONTRIBUTORS
.An -split
.An Maxim Sobolev Aq Mt sobomax@FreeBSD.org
.An Nik Clayton Aq Mt nik@FreeBSD.org
