#!/bin/sh
#echo "run $@" 1>&2
#set -x
# $1 command
# $2 rulename
# $3 protocol
# $4 address
# $5 mask
# $6 port
# $7 id

pf=
if [ -f "/etc/ipfw-blocklist.rc" ]; then
	pf="ipfw"
	. /etc/ipfw-blocklist.rc
	ipfw_offset=${ipfw_offset:-2000}
fi

if [ -z "$pf" ]; then
	for f in npf ipfw; do
		if [ -x /etc/rc.d/$f ]; then
			if /etc/rc.d/$f status >/dev/null 2>&1; then
				pf="$f"
				break
			fi
		elif [ -f "/etc/$f.conf" ]; then
			# xxx assume a config file means it can be enabled --
			# and the first one wins!
			pf="$f"
			break
		fi
	done
fi

if [ -z "$pf" -a -x "/sbin/iptables" ]; then
	pf="iptables"
fi

if [ -z "$pf" ]; then
	echo "$0: Unsupported packet filter" 1>&2
	exit 1
fi

ipfw_offset=${ipfw_offset:-2000}

flags=
if [ -n "$3" ]; then
	raw_proto="$3"
	proto="proto $3"
	if [ $3 = "tcp" ]; then
		flags="flags S/SAFR"
	fi
fi

if [ -n "$6" ]; then
	raw_port="$6"
	port="port $6"
fi

addr="$4"
mask="$5"
case "$4" in
::ffff:*.*.*.*)
	if [ "$5" = 128 ]; then
		mask=32
		addr=${4#::ffff:}
	fi;;
esac

case "$1" in
add)
	case "$pf" in

	ipfw)
		# use $ipfw_offset+$port for rule number
		rule=$(($ipfw_offset + $6))
		tname="port$6"
		/sbin/ipfw table $tname create type addr 2>/dev/null
		/sbin/ipfw -q table $tname add "$addr/$mask"
		# if rule number $rule does not already exist, create it
		/sbin/ipfw show $rule >/dev/null 2>&1 || \
			/sbin/ipfw add $rule drop $3 from \
			table"("$tname")" to any dst-port $6 >/dev/null && \
			echo OK
		;;

	iptables)
		if ! /sbin/iptables --list "$2" >/dev/null 2>&1; then
			/sbin/iptables --new-chain "$2"
		fi
		/sbin/iptables --append INPUT --proto "$raw_proto" \
		    --dport "$raw_port" --jump "$2"
		/sbin/iptables --append "$2" --proto "$raw_proto" \
		    --source "$addr/$mask" --dport "$raw_port" --jump DROP
		echo OK
		;;

	npf)
		/sbin/npfctl rule "$2" add block in final $proto from \
		    "$addr/$mask" to any $port
		;;


	esac
	;;
rem)
	case "$pf" in

	ipfw)
		/sbin/ipfw table "port$6" delete "$addr/$mask" 2>/dev/null && \
		    echo OK
		;;

	iptables)
		if /sbin/iptables --list "$2" >/dev/null 2>&1; then
			/sbin/iptables --delete "$2" --proto "$raw_proto" \
			    --source "$addr/$mask" --dport "$raw_port" \
			    --jump DROP
		fi
		echo OK
		;;

	npf)
		/sbin/npfctl rule "$2" rem-id "$7"
		;;


	esac
	;;
flush)
	case "$pf" in

	ipfw)
		/sbin/ipfw table "port$6" flush 2>/dev/null && echo OK
		;;

	iptables)
		if /sbin/iptables --list "$2" >/dev/null 2>&1; then
			/sbin/iptables --flush "$2"
		fi
		echo OK
		;;

	npf)
		/sbin/npfctl rule "$2" flush
		;;

	esac
	;;
*)
	echo "$0: Unknown command '$1'" 1>&2
	exit 1
	;;
esac
